name: "Jessie 贾惠妤"
email: "hj359@cornell.edu"
description: "Jessie 贾惠妤 is a researcher and filmmaker exploring human–AI interaction, creative AI, and filmmaking."
googleVerification: "a1Jzd5MCuOw3qKQv7QDBGpF3qcKWR4YTUwtyYkqpKrU"
cv: null
social:
  -
    label: "Instagram"
    url: "https://www.instagram.com/j.xjia_/"
  -
    label: "Letterboxd"
    url: "https://letterboxd.com/JieC_x/"
